#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DEFAULT_BUNNY2_DIR=""
if [ -d "$ROOT_DIR/../bunny2" ]; then
  DEFAULT_BUNNY2_DIR="$(cd "$ROOT_DIR/../bunny2" && pwd)"
fi

BUNNY2_DIR="${BUNNY2_DIR:-$DEFAULT_BUNNY2_DIR}"
MODEL_ROOT="${BUNNY_MODEL_ROOT:-$ROOT_DIR/models}"
WHISPER_CLI_PATH="${BUNNY_WHISPER_CPP_BINARY:-$(command -v whisper-cli || true)}"
if [ -z "${UVICORN_BIN:-}" ]; then
  if [ -x "$ROOT_DIR/.venv/bin/uvicorn" ]; then
    UVICORN_BIN="$ROOT_DIR/.venv/bin/uvicorn"
  elif [ -n "$BUNNY2_DIR" ] && [ -x "$BUNNY2_DIR/.venv/bin/uvicorn" ]; then
    UVICORN_BIN="$BUNNY2_DIR/.venv/bin/uvicorn"
  else
    UVICORN_BIN="$(command -v uvicorn || true)"
  fi
fi
HOST="${BUNNY_HOST:-0.0.0.0}"
PORT="${BUNNY_PORT:-8000}"
DEFAULT_TURBO_MODEL="$MODEL_ROOT/whisper/ggml-large-v3-turbo.bin"
DEFAULT_SMALL_MODEL="$MODEL_ROOT/whisper/ggml-small.bin"
HEALTH_URL="http://127.0.0.1:$PORT/healthz"

if [ ! -d "$MODEL_ROOT" ] && [ -n "$BUNNY2_DIR" ] && [ -d "$BUNNY2_DIR/models" ]; then
  MODEL_ROOT="$BUNNY2_DIR/models"
  DEFAULT_TURBO_MODEL="$MODEL_ROOT/whisper/ggml-large-v3-turbo.bin"
  DEFAULT_SMALL_MODEL="$MODEL_ROOT/whisper/ggml-small.bin"
fi

ensure_reserved_port_is_available() {
  if ! lsof -nP -iTCP:"$PORT" -sTCP:LISTEN >/dev/null 2>&1; then
    return 0
  fi

  if curl -s --max-time 3 "$HEALTH_URL" >/dev/null 2>&1; then
    echo "Bunny backend is already running on $HEALTH_URL"
    exit 0
  fi

  echo "Port $PORT is already in use by another service."
  echo "Bunny reserves port $PORT on this Mac."
  echo "Keep Bunny on 8000 and move other local projects to a different port such as 8010."
  lsof -nP -iTCP:"$PORT" -sTCP:LISTEN || true
  exit 1
}

if [ ! -x "$UVICORN_BIN" ]; then
  echo "uvicorn was not found at $UVICORN_BIN"
  echo "Set UVICORN_BIN or prepare the bunny2 virtualenv first."
  exit 1
fi

if [ -z "$WHISPER_CLI_PATH" ]; then
  echo "whisper-cli was not found in PATH."
  echo "Install whisper.cpp or set BUNNY_WHISPER_CPP_BINARY first."
  exit 1
fi

ensure_reserved_port_is_available

export BUNNY_ASR_ENGINE="${BUNNY_ASR_ENGINE:-whisper_cpp}"
export BUNNY_WHISPER_CPP_BINARY="$WHISPER_CLI_PATH"
if [ -z "${BUNNY_WHISPER_MODEL_PATH:-}" ]; then
  if [ -f "$DEFAULT_TURBO_MODEL" ]; then
    export BUNNY_WHISPER_MODEL_PATH="$DEFAULT_TURBO_MODEL"
  else
    export BUNNY_WHISPER_MODEL_PATH="$DEFAULT_SMALL_MODEL"
  fi
fi
export BUNNY_WHISPER_LANGUAGE="${BUNNY_WHISPER_LANGUAGE:-auto}"
export BUNNY_WHISPER_CPP_NO_GPU="${BUNNY_WHISPER_CPP_NO_GPU:-false}"
export BUNNY_WHISPER_CPP_USE_VAD="${BUNNY_WHISPER_CPP_USE_VAD:-true}"
export BUNNY_WHISPER_VAD_MODEL_PATH="${BUNNY_WHISPER_VAD_MODEL_PATH:-$MODEL_ROOT/whisper/ggml-silero-v6.2.0.bin}"
export BUNNY_WHISPER_CPP_SUPPRESS_NON_SPEECH="${BUNNY_WHISPER_CPP_SUPPRESS_NON_SPEECH:-true}"
export BUNNY_WHISPER_CPP_NO_FALLBACK="${BUNNY_WHISPER_CPP_NO_FALLBACK:-false}"
export BUNNY_WHISPER_THREADS="${BUNNY_WHISPER_THREADS:-4}"
export BUNNY_WHISPER_PROCESSORS="${BUNNY_WHISPER_PROCESSORS:-1}"
export BUNNY_WHISPER_PARTIAL_BEAM_SIZE="${BUNNY_WHISPER_PARTIAL_BEAM_SIZE:-3}"
export BUNNY_WHISPER_FINAL_BEAM_SIZE="${BUNNY_WHISPER_FINAL_BEAM_SIZE:-7}"
export BUNNY_WHISPER_NO_SPEECH_THRESHOLD="${BUNNY_WHISPER_NO_SPEECH_THRESHOLD:-0.8}"
export BUNNY_WHISPER_LOGPROB_THRESHOLD="${BUNNY_WHISPER_LOGPROB_THRESHOLD:--0.5}"
export BUNNY_WHISPER_ENTROPY_THRESHOLD="${BUNNY_WHISPER_ENTROPY_THRESHOLD:-2.2}"
export BUNNY_VAD_ENABLED="${BUNNY_VAD_ENABLED:-true}"
export BUNNY_VAD_ENERGY_THRESHOLD="${BUNNY_VAD_ENERGY_THRESHOLD:-0.015}"
export BUNNY_VAD_SILENCE_MS="${BUNNY_VAD_SILENCE_MS:-550}"
export BUNNY_VAD_MIN_SPEECH_MS="${BUNNY_VAD_MIN_SPEECH_MS:-260}"
export BUNNY_VAD_PREROLL_MS="${BUNNY_VAD_PREROLL_MS:-420}"
export BUNNY_UTTERANCE_MAX_MS="${BUNNY_UTTERANCE_MAX_MS:-8000}"
export BUNNY_SEGMENT_EMIT_MS="${BUNNY_SEGMENT_EMIT_MS:-650}"
export BUNNY_SEGMENT_EMIT_BYTES="${BUNNY_SEGMENT_EMIT_BYTES:-16000}"
export BUNNY_PARTIAL_PREVIEW_MS="${BUNNY_PARTIAL_PREVIEW_MS:-2800}"
export BUNNY_LLM_POSTEDIT_SCOPE="${BUNNY_LLM_POSTEDIT_SCOPE:-final}"

export BUNNY_TRANSLATION_ENGINE="${BUNNY_TRANSLATION_ENGINE:-nllb_ct2}"
export BUNNY_TRANSLATION_MODEL_PATH="${BUNNY_TRANSLATION_MODEL_PATH:-$MODEL_ROOT/nllb-200-distilled-600M-ct2}"
export BUNNY_TRANSLATION_TOKENIZER_PATH="${BUNNY_TRANSLATION_TOKENIZER_PATH:-$MODEL_ROOT/nllb-200-distilled-600M-ct2}"
export BUNNY_TRANSLATION_DEVICE="${BUNNY_TRANSLATION_DEVICE:-cpu}"
export BUNNY_TRANSLATION_COMPUTE_TYPE="${BUNNY_TRANSLATION_COMPUTE_TYPE:-int8}"
export BUNNY_TRANSLATION_INTER_THREADS="${BUNNY_TRANSLATION_INTER_THREADS:-2}"
export BUNNY_TRANSLATION_INTRA_THREADS="${BUNNY_TRANSLATION_INTRA_THREADS:-0}"
export BUNNY_TRANSLATION_TARGETS="${BUNNY_TRANSLATION_TARGETS:-[\"ko\",\"es\"]}"
export BUNNY_LLM_POSTEDIT_ENABLED="${BUNNY_LLM_POSTEDIT_ENABLED:-true}"
export BUNNY_LLM_POSTEDIT_BASE_URL="${BUNNY_LLM_POSTEDIT_BASE_URL:-http://127.0.0.1:11434/v1}"
export BUNNY_LLM_POSTEDIT_API_KEY="${BUNNY_LLM_POSTEDIT_API_KEY:-}"
export BUNNY_LLM_POSTEDIT_MODEL="${BUNNY_LLM_POSTEDIT_MODEL:-qwen2.5:7b-instruct}"
export BUNNY_LLM_POSTEDIT_TIMEOUT_S="${BUNNY_LLM_POSTEDIT_TIMEOUT_S:-8}"
export BUNNY_LLM_POSTEDIT_HISTORY_TURNS="${BUNNY_LLM_POSTEDIT_HISTORY_TURNS:-4}"

export BUNNY_ROOM_STORE_BACKEND="${BUNNY_ROOM_STORE_BACKEND:-sqlite}"
export BUNNY_ROOM_STORE_PATH="${BUNNY_ROOM_STORE_PATH:-$ROOT_DIR/data/bunny_app.sqlite3}"
export BUNNY_ROOM_MAX_PARTICIPANTS="${BUNNY_ROOM_MAX_PARTICIPANTS:-5}"
export BUNNY_ROOM_TTL_MINUTES="${BUNNY_ROOM_TTL_MINUTES:-1440}"
export BUNNY_ROOM_CLEANUP_INTERVAL_SECONDS="${BUNNY_ROOM_CLEANUP_INTERVAL_SECONDS:-300}"

cd "$ROOT_DIR"
export PYTHONPATH="$ROOT_DIR${PYTHONPATH:+:$PYTHONPATH}"

echo "Starting bunny-app real demo mode"
echo "ASR: $BUNNY_ASR_ENGINE"
echo "Translation: $BUNNY_TRANSLATION_ENGINE"
echo "Whisper model: $BUNNY_WHISPER_MODEL_PATH"
echo "Translation model: $BUNNY_TRANSLATION_MODEL_PATH"
echo "Listening on: $HOST:$PORT"

exec "$UVICORN_BIN" app.main:app --host "$HOST" --port "$PORT"
